python run.py configs/mvtec.yaml --multirun params.cross_validation=0,1,2,3,4 params.category=bottle
python run.py configs/mvtec.yaml --multirun params.cross_validation=0,1,2,3,4 params.category=cable
python run.py configs/mvtec.yaml --multirun params.cross_validation=0,1,2,3,4 params.category=capsule
python run.py configs/mvtec.yaml --multirun params.cross_validation=0,1,2,3,4 params.category=carpet
python run.py configs/mvtec.yaml --multirun params.cross_validation=0,1,2,3,4 params.category=grid
python run.py configs/mvtec.yaml --multirun params.cross_validation=0,1,2,3,4 params.category=hazelnut
python run.py configs/mvtec.yaml --multirun params.cross_validation=0,1,2,3,4 params.category=leather
python run.py configs/mvtec.yaml --multirun params.cross_validation=0,1,2,3,4 params.category=metal_nut
python run.py configs/mvtec.yaml --multirun params.cross_validation=0,1,2,3,4 params.category=pill
python run.py configs/mvtec.yaml --multirun params.cross_validation=0,1,2,3,4 params.category=screw
python run.py configs/mvtec.yaml --multirun params.cross_validation=0,1,2,3,4 params.category=tile
python run.py configs/mvtec.yaml --multirun params.cross_validation=0,1,2,3,4 params.category=toothbrush
python run.py configs/mvtec.yaml --multirun params.cross_validation=0,1,2,3,4 params.category=transistor
python run.py configs/mvtec.yaml --multirun params.cross_validation=0,1,2,3,4 params.category=wood
python run.py configs/mvtec.yaml --multirun params.cross_validation=0,1,2,3,4 params.category=zipper
